[build-system]
requires = ["flit_core >=3.2,<4", "sphinx-book-theme"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Graziella", email = "graziella@lumache"}]
dynamic = ["version", "description"]
